export const MockData = [
    {
        "Location": { "S": "New York,US" },
        "Description": { "S": "overcast clouds" },
        "Main": { "S": "Clear" },
        "Temperature": { "N": "74" },
        "FeelsLike": { "N": "273.25" },
        "Humidity": { "N": "27" },
        "Speed": { "N": "5" },
        "Timestamp": { "S": '2023-11-22T22:55:21.693Z' },
        "TempMin": { "N": "70" },
        "TempMax": { "N": "81" },
        "Rain": { "N": ".16" },
        "Day1Temp": { "N": '75' },
        "Day1TempMax": { "N": '77' },
        "Day1TempMin": { "N": '72' },
        "Day2Temp": { "N": '71' },
        "Day2TempMax": { "N": '75' },
        "Day2TempMin": { "N": '68' },
        "Day3Temp": { "N": '80' },
        "Day3TempMax": { "N": '83' },
        "Day3TempMin": { "N": '77' },
        "Day4Temp": { "N": '79' },
        "Day4TempMax": { "N": '81' },
        "Day4TempMin": { "N": '76' },
        "Day5Temp": { "N": '73' },
        "Day5TempMax": { "N": '77' },
        "Day5TempMin": { "N": '71' }
    },
    {
        "Location": { "S": "Calabasas,US" },
        "Description": { "S": "clear sky" },
        "Main": { "S": "Clear" },
        "Temperature": { "N": "50" },
        "FeelsLike": { "N": "273.25" },
        "Humidity": { "N": "45" },
        "Speed": { "N": "12" },
        "Timestamp": { "S": '2023-11-14T01:22:53.945Z' },
        "TempMin": { "N": "56" },
        "TempMax": { "N": "69" },
        "Rain": { "N": ".04" },
        "Day1Temp": { "N": '51' },
        "Day1TempMax": { "N": '54' },
        "Day1TempMin": { "N": '48' },
        "Day2Temp": { "N": '47' },
        "Day2TempMax": { "N": '51' },
        "Day2TempMin": { "N": '44' },
        "Day3Temp": { "N": '56' },
        "Day3TempMax": { "N": '60' },
        "Day3TempMin": { "N": '54' },
        "Day4Temp": { "N": '58' },
        "Day4TempMax": { "N": '61' },
        "Day4TempMin": { "N": '56' },
        "Day5Temp": { "N": '53' },
        "Day5TempMax": { "N": '57' },
        "Day5TempMin": { "N": '50' }
    },
    {
        "Location": { "S": "Los Angeles,US" },
        "Description": { "S": "clear sky" },
        "Main": { "S": "Clear" },
        "Temperature": { "N": "70" },
        "FeelsLike": { "N": "273.25" },
        "Humidity": { "N": "45" },
        "Speed": { "N": "18" },
        "Timestamp": { "S": '2023-11-22T23:08:37.080Z' },
        "TempMin": { "N": "67" },
        "TempMax": { "N": "72" },
        "Rain": { "N": "0" },
        "Day1Temp": { "N": '71' },
        "Day1TempMax": { "N": '73' },
        "Day1TempMin": { "N": '69' },
        "Day2Temp": { "N": '68' },
        "Day2TempMax": { "N": '71' },
        "Day2TempMin": { "N": '65' },
        "Day3Temp": { "N": '74' },
        "Day3TempMax": { "N": '76' },
        "Day3TempMin": { "N": '70' },
        "Day4Temp": { "N": '75' },
        "Day4TempMax": { "N": '77' },
        "Day4TempMin": { "N": '73' },
        "Day5Temp": { "N": '69' },
        "Day5TempMax": { "N": '72' },
        "Day5TempMin": { "N": '66' }
    },
    {
        "Location": { "S": "Akron,US" },
        "Description": { "S": "mist" },
        "Main": { "S": "Clear" },
        "Temperature": { "N": "45" },
        "FeelsLike": { "N": "273.25" },
        "Humidity": { "N": "24" },
        "Speed": { "N": "3" },
        "Timestamp": { "S": '2023-12-03T22:11:05.429Z' },
        "TempMin": { "N": "40" },
        "TempMax": { "N": "52" },
        "Rain": { "N": ".30" },
        "Day1Temp": { "N": '46' },
        "Day1TempMax": { "N": '48' },
        "Day1TempMin": { "N": '43' },
        "Day2Temp": { "N": '42' },
        "Day2TempMax": { "N": '46' },
        "Day2TempMin": { "N": '39' },
        "Day3Temp": { "N": '51' },
        "Day3TempMax": { "N": '54' },
        "Day3TempMin": { "N": '48' },
        "Day4Temp": { "N": '50' },
        "Day4TempMax": { "N": '52' },
        "Day4TempMin": { "N": '47' },
        "Day5Temp": { "N": '44' },
        "Day5TempMax": { "N": '48' },
        "Day5TempMin": { "N": '42' }
    },
];
