export const citiestz = [{ name: "Aberdeen", timeZone: "America/Chicago" },
{ name: "Abilene", timeZone: "America/Chicago" },
{ name: "Akron", timeZone: "America/New_York" },
{ name: "Albany", timeZone: "America/New_York" },
{ name: "Albuquerque", timeZone: "America/Denver" },
{ name: "Alexandria", timeZone: "America/New_York" },
{ name: "Allentown", timeZone: "America/New_York" },
{ name: "Amarillo", timeZone: "America/Chicago" },
{ name: "Anaheim", timeZone: "America/Los_Angeles" },
{ name: "Anchorage", timeZone: "America/Anchorage" },
{ name: "Ann Arbor", timeZone: "America/New_York" },
{ name: "Antioch", timeZone: "America/Los_Angeles" },
{ name: "Apple Valley", timeZone: "America/Los_Angeles" },
{ name: "Appleton", timeZone: "America/Chicago" },
{ name: "Arlington", timeZone: "America/New_York" },
{ name: "Arvada", timeZone: "America/Denver" },
{ name: "Asheville", timeZone: "America/New_York" },
{ name: "Athens", timeZone: "America/New_York" },
{ name: "Atlanta", timeZone: "America/New_York" },
{ name: "Atlantic City", timeZone: "America/New_York" },
{ name: "Augusta", timeZone: "America/New_York" },
{ name: "Aurora", timeZone: "America/Denver" },
{ name: "Austin", timeZone: "America/Chicago" },
{ name: "Bakersfield", timeZone: "America/Los_Angeles" },
{ name: "Baltimore", timeZone: "America/New_York" },
{ name: "Barnstable", timeZone: "America/New_York" },
{ name: "Baton Rouge", timeZone: "America/Chicago" },
{ name: "Beaumont", timeZone: "America/Chicago" },
{ name: "Bel Air", timeZone: "America/New_York" },
{ name: "Bellevue", timeZone: "America/Los_Angeles" },
{ name: "Berkeley", timeZone: "America/Los_Angeles" },
{ name: "Bethlehem", timeZone: "America/New_York" },
{ name: "Billings", timeZone: "America/Denver" },
{ name: "Birmingham", timeZone: "America/Chicago" },
{ name: "Bloomington", timeZone: "America/Chicago" },
{ name: "Boise", timeZone: "America/Denver" },
{ name: "Boise City", timeZone: "America/Denver" },
{ name: "Bonita Springs", timeZone: "America/New_York" },
{ name: "Boston", timeZone: "America/New_York" },
{ name: "Boulder", timeZone: "America/Denver" },
{ name: "Bradenton", timeZone: "America/New_York" },
{ name: "Bremerton", timeZone: "America/Los_Angeles" },
{ name: "Bridgeport", timeZone: "America/New_York" },
{ name: "Brighton", timeZone: "America/New_York" },
{ name: "Brownsville", timeZone: "America/Chicago" },
{ name: "Bryan", timeZone: "America/Chicago" },
{ name: "Buffalo", timeZone: "America/New_York" },
{ name: "Burbank", timeZone: "America/Los_Angeles" },
{ name: "Burlington", timeZone: "America/New_York" },
{ name: "Cambridge", timeZone: "America/New_York" },
{ name: "Calabasas", timeZone: "America/Los_Angeles" },
{ name: "Canton", timeZone: "America/New_York" },
{ name: "Cape Coral", timeZone: "America/New_York" },
{ name: "Carrollton", timeZone: "America/Chicago" },
{ name: "Cary", timeZone: "America/New_York" },
{ name: "Cathedral City", timeZone: "America/Los_Angeles" },
{ name: "Cedar Rapids", timeZone: "America/Chicago" },
{ name: "Champaign", timeZone: "America/Chicago" },
{ name: "Chandler", timeZone: "America/Phoenix" },
{ name: "Charleston", timeZone: "America/New_York" },
{ name: "Charlotte", timeZone: "America/New_York" },
{ name: "Chattanooga", timeZone: "America/New_York" },
{ name: "Chesapeake", timeZone: "America/New_York" },
{ name: "Chicago", timeZone: "America/Chicago" },
{ name: "Chula Vista", timeZone: "America/Los_Angeles" },
{ name: "Cincinnati", timeZone: "America/New_York" },
{ name: "Clarke County", timeZone: "America/New_York" },
{ name: "Clarksville", timeZone: "America/Chicago" },
{ name: "Clearwater", timeZone: "America/New_York" },
{ name: "Cleveland", timeZone: "America/New_York" },
{ name: "College Station", timeZone: "America/Chicago" },
{ name: "Colorado Springs", timeZone: "America/Denver" },
{ name: "Columbia", timeZone: "America/New_York" },
{ name: "Columbus", timeZone: "America/New_York" },
{ name: "Concord", timeZone: "America/New_York" },
{ name: "Coral Springs", timeZone: "America/New_York" },
{ name: "Corona", timeZone: "America/Los_Angeles" },
{ name: "Corpus Christi", timeZone: "America/Chicago" },
{ name: "Costa Mesa", timeZone: "America/Los_Angeles" },
{ name: "Dallas", timeZone: "America/Chicago" },
{ name: "Daly City", timeZone: "America/Los_Angeles" },
{ name: "Danbury", timeZone: "America/New_York" },
{ name: "Davenport", timeZone: "America/Chicago" },
{ name: "Davidson County", timeZone: "America/New_York" },
{ name: "Dayton", timeZone: "America/New_York" },
{ name: "Daytona Beach", timeZone: "America/New_York" },
{ name: "Deltona", timeZone: "America/New_York" },
{ name: "Denton", timeZone: "America/Chicago" },
{ name: "Denver", timeZone: "America/Denver" },
{ name: "Des Moines", timeZone: "America/Chicago" },
{ name: "Detroit", timeZone: "America/New_York" },
{ name: "Downey", timeZone: "America/Los_Angeles" },
{ name: "Duluth", timeZone: "America/Chicago" },
{ name: "Durham", timeZone: "America/New_York" },
{ name: "El Monte", timeZone: "America/Los_Angeles" },
{ name: "El Paso", timeZone: "America/Denver" },
{ name: "Elizabeth", timeZone: "America/New_York" },
{ name: "Elk Grove", timeZone: "America/Los_Angeles" },
{ name: "Elkhart", timeZone: "America/Chicago" },
{ name: "Erie", timeZone: "America/New_York" },
{ name: "Escondido", timeZone: "America/Los_Angeles" },
{ name: "Eugene", timeZone: "America/Los_Angeles" },
{ name: "Evansville", timeZone: "America/Chicago" },
{ name: "Fairfield", timeZone: "America/New_York" },
{ name: "Fargo", timeZone: "America/Chicago" },
{ name: "Fayetteville", timeZone: "America/New_York" },
{ name: "Fitchburg", timeZone: "America/New_York" },
{ name: "Flint", timeZone: "America/New_York" },
{ name: "Fontana", timeZone: "America/Los_Angeles" },
{ name: "Fort Collins", timeZone: "America/Denver" },
{ name: "Fort Lauderdale", timeZone: "America/New_York" },
{ name: "Fort Smith", timeZone: "America/Chicago" },
{ name: "Fort Walton Beach", timeZone: "America/Chicago" },
{ name: "Fort Wayne", timeZone: "America/New_York" },
{ name: "Fort Worth", timeZone: "America/Chicago" },
{ name: "Frederick", timeZone: "America/New_York" },
{ name: "Fremont", timeZone: "America/Los_Angeles" },
{ name: "Fresno", timeZone: "America/Los_Angeles" },
{ name: "Fullerton", timeZone: "America/Los_Angeles" },
{ name: "Gainesville", timeZone: "America/New_York" },
{ name: "Garden Grove", timeZone: "America/Los_Angeles" },
{ name: "Garland", timeZone: "America/Chicago" },
{ name: "Gastonia", timeZone: "America/New_York" },
{ name: "Gilbert", timeZone: "America/Phoenix" },
{ name: "Glendale", timeZone: "America/Los_Angeles" },
{ name: "Grand Prairie", timeZone: "America/Chicago" },
{ name: "Grand Rapids", timeZone: "America/New_York" },
{ name: "Grayslake", timeZone: "America/Chicago" },
{ name: "Green Bay", timeZone: "America/Chicago" },
{ name: "GreenBay", timeZone: "America/Chicago" },
{ name: "Greensboro", timeZone: "America/New_York" },
{ name: "Greenville", timeZone: "America/New_York" },
{ name: "Gulfport-Biloxi", timeZone: "America/Chicago" },
{ name: "Hagerstown", timeZone: "America/New_York" },
{ name: "Hampton", timeZone: "America/New_York" },
{ name: "Harlingen", timeZone: "America/Chicago" },
{ name: "Harrisburg", timeZone: "America/New_York" },
{ name: "Hartford", timeZone: "America/New_York" },
{ name: "Havre de Grace", timeZone: "America/New_York" },
{ name: "Hayward", timeZone: "America/Los_Angeles" },
{ name: "Hemet", timeZone: "America/Los_Angeles" },
{ name: "Henderson", timeZone: "America/Los_Angeles" },
{ name: "Hesperia", timeZone: "America/Los_Angeles" },
{ name: "Hialeah", timeZone: "America/New_York" },
{ name: "Hickory", timeZone: "America/New_York" },
{ name: "High Point", timeZone: "America/New_York" },
{ name: "Hollywood", timeZone: "America/New_York" },
{ name: "Honolulu", timeZone: "Pacific/Honolulu" },
{ name: "Houma", timeZone: "America/Chicago" },
{ name: "Houston", timeZone: "America/Chicago" },
{ name: "Howell", timeZone: "America/New_York" },
{ name: "Huntington", timeZone: "America/New_York" },
{ name: "Huntington Beach", timeZone: "America/Los_Angeles" },
{ name: "Huntsville", timeZone: "America/Chicago" },
{ name: "Independence", timeZone: "America/Chicago" },
{ name: "Indianapolis", timeZone: "America/Indiana/Indianapolis" },
{ name: "Inglewood", timeZone: "America/Los_Angeles" },
{ name: "Irvine", timeZone: "America/Los_Angeles" },
{ name: "Irving", timeZone: "America/Chicago" },
{ name: "Jackson", timeZone: "America/Chicago" },
{ name: "Jacksonville", timeZone: "America/New_York" },
{ name: "Jefferson", timeZone: "America/New_York" },
{ name: "Jersey City", timeZone: "America/New_York" },
{ name: "Johnson City", timeZone: "America/New_York" },
{ name: "Joliet", timeZone: "America/Chicago" },
{ name: "Kailua", timeZone: "Pacific/Honolulu" },
{ name: "Kalamazoo", timeZone: "America/Detroit" },
{ name: "Kaneohe", timeZone: "Pacific/Honolulu" },
{ name: "Kansas City", timeZone: "America/Chicago" },
{ name: "Kennewick", timeZone: "America/Los_Angeles" },
{ name: "Kenosha", timeZone: "America/Chicago" },
{ name: "Killeen", timeZone: "America/Chicago" },
{ name: "Kissimmee", timeZone: "America/New_York" },
{ name: "Knoxville", timeZone: "America/New_York" },
{ name: "Lacey", timeZone: "America/Los_Angeles" },
{ name: "Lafayette", timeZone: "America/Chicago" },
{ name: "Lake Charles", timeZone: "America/Chicago" },
{ name: "Lakeland", timeZone: "America/New_York" },
{ name: "Lakewood", timeZone: "America/Denver" },
{ name: "Lancaster", timeZone: "America/New_York" },
{ name: "Lansing", timeZone: "America/Detroit" },
{ name: "Laredo", timeZone: "America/Chicago" },
{ name: "Las Cruces", timeZone: "America/Denver" },
{ name: "Las Vegas", timeZone: "America/Los_Angeles" },
{ name: "Layton", timeZone: "America/Denver" },
{ name: "Leominster", timeZone: "America/New_York" },
{ name: "Lewisville", timeZone: "America/Chicago" },
{ name: "Lexington", timeZone: "America/New_York" },
{ name: "Lincoln", timeZone: "America/Chicago" },
{ name: "Little Rock", timeZone: "America/Chicago" },
{ name: "Long Beach", timeZone: "America/Los_Angeles" },
{ name: "Lorain", timeZone: "America/New_York" },
{ name: "Los Angeles", timeZone: "America/Los_Angeles" },
{ name: "Louisville", timeZone: "America/New_York" },
{ name: "Lowell", timeZone: "America/New_York" },
{ name: "Lubbock", timeZone: "America/Chicago" },
{ name: "Macon", timeZone: "America/New_York" },
{ name: "Madison", timeZone: "America/Chicago" },
{ name: "Manchester", timeZone: "America/New_York" },
{ name: "Marina", timeZone: "America/Los_Angeles" },
{ name: "Marysville", timeZone: "America/Los_Angeles" },
{ name: "McAllen", timeZone: "America/Chicago" },
{ name: "McHenry", timeZone: "America/Chicago" },
{ name: "Medford", timeZone: "America/Los_Angeles" },
{ name: "Melbourne", timeZone: "America/New_York" },
{ name: "Memphis", timeZone: "America/Chicago" },
{ name: "Merced", timeZone: "America/Los_Angeles" },
{ name: "Mesa", timeZone: "America/Phoenix" },
{ name: "Mesquite", timeZone: "America/Chicago" },
{ name: "Miami", timeZone: "America/New_York" },
{ name: "Milwaukee", timeZone: "America/Chicago" },
{ name: "Minneapolis", timeZone: "America/Chicago" },
{ name: "Miramar", timeZone: "America/New_York" },
{ name: "Mission Viejo", timeZone: "America/Los_Angeles" },
{ name: "Mobile", timeZone: "America/Chicago" },
{ name: "Modesto", timeZone: "America/Los_Angeles" },
{ name: "Monroe", timeZone: "America/New_York" },
{ name: "Monterey", timeZone: "America/Los_Angeles" },
{ name: "Montgomery", timeZone: "America/Chicago" },
{ name: "Moreno Valley", timeZone: "America/Los_Angeles" },
{ name: "Murfreesboro", timeZone: "America/Chicago" },
{ name: "Murrieta", timeZone: "America/Los_Angeles" },
{ name: "Muskegon", timeZone: "America/Detroit" },
{ name: "Myrtle Beach", timeZone: "America/New_York" },
{ name: "Naperville", timeZone: "America/Chicago" },
{ name: "Naples", timeZone: "America/New_York" },
{ name: "Nashua", timeZone: "America/New_York" },
{ name: "Nashville", timeZone: "America/Chicago" },
{ name: "New Bedford", timeZone: "America/New_York" },
{ name: "New Haven", timeZone: "America/New_York" },
{ name: "New London", timeZone: "America/New_York" },
{ name: "New Orleans", timeZone: "America/Chicago" },
{ name: "New York", timeZone: "America/New_York" },
{ name: "New York City", timeZone: "America/New_York" },
{ name: "Newark", timeZone: "America/New_York" },
{ name: "Newburgh", timeZone: "America/New_York" },
{ name: "Newport News", timeZone: "America/New_York" },
{ name: "Norfolk", timeZone: "America/New_York" },
{ name: "Normal", timeZone: "America/Chicago" },
{ name: "Norman", timeZone: "America/Chicago" },
{ name: "North Charleston", timeZone: "America/New_York" },
{ name: "North Las Vegas", timeZone: "America/Los_Angeles" },
{ name: "North Port", timeZone: "America/New_York" },
{ name: "Norwalk", timeZone: "America/New_York" },
{ name: "Norwich", timeZone: "America/New_York" },
{ name: "Oakland", timeZone: "America/Los_Angeles" },
{ name: "Ocala", timeZone: "America/New_York" },
{ name: "Oceanside", timeZone: "America/Los_Angeles" },
{ name: "Odessa", timeZone: "America/Chicago" },
{ name: "Ogden", timeZone: "America/Denver" },
{ name: "Oklahoma City", timeZone: "America/Chicago" },
{ name: "Olathe", timeZone: "America/Chicago" },
{ name: "Olympia", timeZone: "America/Los_Angeles" },
{ name: "Omaha", timeZone: "America/Chicago" },
{ name: "Ontario", timeZone: "America/Los_Angeles" },
{ name: "Orange", timeZone: "America/Los_Angeles" },
{ name: "Orem", timeZone: "America/Denver" },
{ name: "Orlando", timeZone: "America/New_York" },
{ name: "Overland Park", timeZone: "America/Chicago" },
{ name: "Oxnard", timeZone: "America/Los_Angeles" },
{ name: "Palm Bay", timeZone: "America/New_York" },
{ name: "Palm Springs", timeZone: "America/Los_Angeles" },
{ name: "Palmdale", timeZone: "America/Los_Angeles" },
{ name: "Panama City", timeZone: "America/Chicago" },
{ name: "Pasadena", timeZone: "America/Los_Angeles" },
{ name: "Paterson", timeZone: "America/New_York" },
{ name: "Pembroke Pines", timeZone: "America/New_York" },
{ name: "Pensacola", timeZone: "America/Chicago" },
{ name: "Peoria", timeZone: "America/Chicago" },
{ name: "Philadelphia", timeZone: "America/New_York" },
{ name: "Phoenix", timeZone: "America/Phoenix" },
{ name: "Pittsburgh", timeZone: "America/New_York" },
{ name: "Plano", timeZone: "America/Chicago" },
{ name: "Pomona", timeZone: "America/Los_Angeles" },
{ name: "Pompano Beach", timeZone: "America/New_York" },
{ name: "Port Arthur", timeZone: "America/Chicago" },
{ name: "Port Orange", timeZone: "America/New_York" },
{ name: "Port Saint Lucie", timeZone: "America/New_York" },
{ name: "Port St. Lucie", timeZone: "America/New_York" },
{ name: "Portland", timeZone: "America/Los_Angeles" },
{ name: "Portsmouth", timeZone: "America/New_York" },
{ name: "Poughkeepsie", timeZone: "America/New_York" },
{ name: "Providence", timeZone: "America/New_York" },
{ name: "Provo", timeZone: "America/Denver" },
{ name: "Pueblo", timeZone: "America/Denver" },
{ name: "Punta Gorda", timeZone: "America/New_York" },
{ name: "Racine", timeZone: "America/Chicago" },
{ name: "Raleigh", timeZone: "America/New_York" },
{ name: "Rancho Cucamonga", timeZone: "America/Los_Angeles" },
{ name: "Reading", timeZone: "America/New_York" },
{ name: "Redding", timeZone: "America/Los_Angeles" },
{ name: "Reno", timeZone: "America/Los_Angeles" },
{ name: "Richland", timeZone: "America/Los_Angeles" },
{ name: "Richmond", timeZone: "America/New_York" },
{ name: "Richmond County", timeZone: "America/New_York" },
{ name: "Riverside", timeZone: "America/Los_Angeles" },
{ name: "Roanoke", timeZone: "America/New_York" },
{ name: "Rochester", timeZone: "America/New_York" },
{ name: "Rockford", timeZone: "America/Chicago" },
{ name: "Roseville", timeZone: "America/Los_Angeles" },
{ name: "Round Lake Beach", timeZone: "America/Chicago" },
{ name: "Sacramento", timeZone: "America/Los_Angeles" },
{ name: "Saginaw", timeZone: "America/New_York" },
{ name: "Saint Louis", timeZone: "America/Chicago" },
{ name: "Saint Paul", timeZone: "America/Chicago" },
{ name: "Saint Petersburg", timeZone: "America/New_York" },
{ name: "Salem", timeZone: "America/Los_Angeles" },
{ name: "Salinas", timeZone: "America/Los_Angeles" },
{ name: "Salt Lake City", timeZone: "America/Denver" },
{ name: "San Antonio", timeZone: "America/Chicago" },
{ name: "San Bernardino", timeZone: "America/Los_Angeles" },
{ name: "San Buenaventura", timeZone: "America/Los_Angeles" },
{ name: "San Diego", timeZone: "America/Los_Angeles" },
{ name: "San Francisco", timeZone: "America/Los_Angeles" },
{ name: "San Jose", timeZone: "America/Los_Angeles" },
{ name: "Santa Ana", timeZone: "America/Los_Angeles" },
{ name: "Santa Barbara", timeZone: "America/Los_Angeles" },
{ name: "Santa Clara", timeZone: "America/Los_Angeles" },
{ name: "Santa Clarita", timeZone: "America/Los_Angeles" },
{ name: "Santa Cruz", timeZone: "America/Los_Angeles" },
{ name: "Santa Maria", timeZone: "America/Los_Angeles" },
{ name: "Santa Rosa", timeZone: "America/Los_Angeles" },
{ name: "Sarasota", timeZone: "America/New_York" },
{ name: "Savannah", timeZone: "America/New_York" },
{ name: "Scottsdale", timeZone: "America/Phoenix" },
{ name: "Scranton", timeZone: "America/New_York" },
{ name: "Seaside", timeZone: "America/Los_Angeles" },
{ name: "Seattle", timeZone: "America/Los_Angeles" },
{ name: "Sebastian", timeZone: "America/New_York" },
{ name: "Shreveport", timeZone: "America/Chicago" },
{ name: "Simi Valley", timeZone: "America/Los_Angeles" },
{ name: "Sioux City", timeZone: "America/Chicago" },
{ name: "Sioux Falls", timeZone: "America/Chicago" },
{ name: "South Bend", timeZone: "America/Chicago" },
{ name: "South Lyon", timeZone: "America/Detroit" },
{ name: "Spartanburg", timeZone: "America/New_York" },
{ name: "Spokane", timeZone: "America/Los_Angeles" },
{ name: "Springdale", timeZone: "America/Chicago" },
{ name: "Springfield", timeZone: "America/New_York" },
{ name: "St. Louis", timeZone: "America/Chicago" },
{ name: "St. Paul", timeZone: "America/Chicago" },
{ name: "St. Petersburg", timeZone: "America/New_York" },
{ name: "Stamford", timeZone: "America/New_York" },
{ name: "Sterling Heights", timeZone: "America/Detroit" },
{ name: "Stockton", timeZone: "America/Los_Angeles" },
{ name: "Sunnyvale", timeZone: "America/Los_Angeles" },
{ name: "Syracuse", timeZone: "America/New_York" },
{ name: "Tacoma", timeZone: "America/Los_Angeles" },
{ name: "Tallahassee", timeZone: "America/New_York" },
{ name: "Tampa", timeZone: "America/New_York" },
{ name: "Temecula", timeZone: "America/Los_Angeles" },
{ name: "Tempe", timeZone: "America/Phoenix" },
{ name: "Thornton", timeZone: "America/Denver" },
{ name: "Thousand Oaks", timeZone: "America/Los_Angeles" },
{ name: "Toledo", timeZone: "America/New_York" },
{ name: "Topeka", timeZone: "America/Chicago" },
{ name: "Torrance", timeZone: "America/Los_Angeles" },
{ name: "Trenton", timeZone: "America/New_York" },
{ name: "Tucson", timeZone: "America/Phoenix" },
{ name: "Tulsa", timeZone: "America/Chicago" },
{ name: "Tuscaloosa", timeZone: "America/Chicago" },
{ name: "Tyler", timeZone: "America/Chicago" },
{ name: "Utica", timeZone: "America/New_York" },
{ name: "Vallejo", timeZone: "America/Los_Angeles" },
{ name: "Vancouver", timeZone: "America/Los_Angeles" },
{ name: "Vero Beach", timeZone: "America/New_York" },
{ name: "Victorville", timeZone: "America/Los_Angeles" },
{ name: "Virginia Beach", timeZone: "America/New_York" },
{ name: "Visalia", timeZone: "America/Los_Angeles" },
{ name: "Waco", timeZone: "America/Chicago" },
{ name: "Warren", timeZone: "America/Detroit" },
{ name: "Washington", timeZone: "America/New_York" },
{ name: "Waterbury", timeZone: "America/New_York" },
{ name: "Waterloo", timeZone: "America/Chicago" },
{ name: "West Covina", timeZone: "America/Los_Angeles" },
{ name: "West Valley City", timeZone: "America/Denver" },
{ name: "Westminster", timeZone: "America/Denver" },
{ name: "Wichita", timeZone: "America/Chicago" },
{ name: "Wilmington", timeZone: "America/New_York" },
{ name: "Winston", timeZone: "America/New_York" },
{ name: "Winter Haven", timeZone: "America/New_York" },
{ name: "Worcester", timeZone: "America/New_York" },
{ name: "Yakima", timeZone: "America/Los_Angeles" },
{ name: "Yonkers", timeZone: "America/New_York" },
{ name: "York", timeZone: "America/New_York" },
{ name: "Youngstown", timeZone: "America/New_York" }
]